# Generated by Django 2.2.4 on 2019-09-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
