# Generated by Django 2.2.4 on 2019-09-03 10:05

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190903_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(70)]),
        ),
    ]
