# Generated by Django 2.2.4 on 2019-09-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190903_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('amount', models.PositiveIntegerField()),
                ('donate_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
